version: 0.0 # CodeDeploy 버전(프로젝트 버전 아님!)
os: linux # Linux – Amazon Linux, Ubuntu Server 또는 RHEL 인스턴스 / Windows – Windows Server 인스턴스
files:
  - source: / # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 정합니다. 루트 경로(/)를 지정하면 전체 파일을 이야기합니다.
    destination: /home/ubuntu/app/step2/zip/ # source에서 지정된 파일을 받을 위치. Jar 실행은 옮긴 파일들로 징행
    overwrite: yes # 기존에 파일이 있으면 덮어쓸지 결정(yes: 덮어쓰겠다)
