version: 0.0 # CodeDeploy 버전(프로젝트 버전 아님!)
os: linux # Linux – Amazon Linux, Ubuntu Server 또는 RHEL 인스턴스 / Windows – Windows Server 인스턴스
files:
  - source: / # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 정합니다. 루트 경로(/)를 지정하면 전체 파일을 이야기합니다.
    destination: /home/ubuntu/app/step2/zip/ # source에서 지정된 파일을 받을 위치. Jar 실행은 옮긴 파일들로 징행
    overwrite: yes # 기존에 파일이 있으면 덮어쓸지 결정(yes: 덮어쓰겠다)

permissions:  # CodeDeploy에서 EC2로 넘겨준 파일들을 모두 ubuntu(os 사용자이름)가 권한을 갖도록 설정
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:  # CodeDeploy 배포 단계에서 실행할 명령어 지정.
  ApplicationStart: # ApplicationStart 단계에서 deploy.sh를 ubuntu 권한으로 실행
    - location: deploy.sh
      timeout: 60 # timeout 60으로 스크립트 실행 60초 이상 수행되면 실패(무한정 기다릴 수 없으므로 시간 제한 필요함)
      runas: ubuntu